### ISSUE TITLE
Input content overflow

### ISSUE THREAD

**Issue by aiemoji** [elevenBeans/ReactCalculater#1]
![image](https://cloud.githubusercontent.com/assets/26480986/24448184/e6f3125c-14a5-11e7-8a0e-73bf7789911e.png)

.pannel .text-right p {
    font-size: 40px;
    line-height: 55px;
    margin: 0 0 10px;
//You can set "overflow-x:auto".
    overflow-x: auto;
}

**Comment by elevenbeans** [comment]
sorry to reply so later, I will fixed it, thanks bro ~

**Comment by elevenbeans** [comment]
BTW, here is my new project [weVoting](https://github.com/elevenBeans/WeVoting)

I am looking forward to receiving issues and improvements from you～
